Initial commit

diff --git a/luci-app-socat-js/root/etc/init.d/socat2 b/luci-app-socat-js/root/etc/init.d/socat2
--- a/luci-app-socat-js/root/etc/init.d/socat2
+++ b/luci-app-socat-js/root/etc/init.d/socat2
@@ -9,7 +9,7 @@ CONFIG_PATH="/var/etc/$CONFIG"
 BIN="/usr/bin/socat"
 NFTABLES=false
 
-prepare_args() {
+load_config_values() {
 	local section="$1"
 
 	config_get enable "$section" enable
@@ -18,7 +18,6 @@ prepare_args() {
 	config_get remarks "$section" remarks
 	config_get protocol "$section" protocol
 	config_get family "$section" family
-	[ "$family" = "4/6" ] && family=""
 	config_get proto "$section" proto
 	config_get listen_port "$section" listen_port
 	config_get reuseaddr "$section" reuseaddr
@@ -30,40 +29,69 @@ prepare_args() {
 	config_get proxy_server "$section" proxy_server
 	config_get proxy_port "$section" proxy_port
 
-	[ "$reuseaddr" = "1" ] && reuseaddr=",reuseaddr" || reuseaddr=""
-	[ "$family" = "6" ] && ipv6only=",ipv6-v6only" || ipv6only=""
+	return 0
+}
 
-	local listen="${proto}${family}"
-	[ -z "$family" ] && listen="${proto}6"
+build_socat_command() {
+	local section="$1"
+	load_config_values "$section" || return 1
 
+	[ "$reuseaddr" = "1" ] && reusearg=",reuseaddr" || reusearg=""
+
+	case "$family" in
+		4)
+			listen_proto="${proto}4"
+			ipv6arg=""
+			;;
+		6)
+			listen_proto="${proto}6"
+			ipv6arg=",ipv6-v6only"
+			;;
+		4/6)
+			listen_proto="${proto}6"
+			ipv6arg=""
+			;;
+		*)
+			echo "[$section] Invalid family value: '$family'" >&2
+			return 1
+			;;
+	esac
+
+	# Proxy settings
+	local proxy_dest=""
 	local proxy_arg=""
 	if [ -n "$proxy" ]; then
 		case "$proxy" in
-			"socks4/4a")
+			socks4/4a)
 				dest_proto="socks4a"
 				proxy_arg="socksport"
 				;;
-			"http")
+			http)
 				dest_proto="proxy"
 				proxy_arg="proxyport"
 				;;
 		esac
 		[ -n "$proxy_server" ] && dest_proto="${dest_proto}:${proxy_server}"
-		[ -n "$proxy_port" ] && proxy_arg=",${proxy_arg}=${proxy_port}"
+		[ -n "$proxy_port" ] && proxy_dest=",${proxy_arg}=${proxy_port}"
 	fi
 
-	CMD="${CONFIG_PATH}/${section} ${listen}-listen:${listen_port}${ipv6only}${reuseaddr},fork ${dest_proto}:${dest_ip}:${dest_port}${proxy_arg}"
+	# socat args as array (procd-friendly)
+	local listen_arg="${listen_proto}-listen:${listen_port}${ipv6arg}${reusearg},fork"
+	local dest_arg="${dest_proto}:${dest_ip}:${dest_port}${proxy_dest}"
+
+	SOCAT_CMD_ARGS="$listen_arg $dest_arg"
 	return 0
 }
 
 start_instance() {
 	local section="$1"
-	prepare_args "$section" || return 0
+	build_socat_command "$section" || return 0
 	add_firewall_rule "$section"
-	ln -sf "$BIN" "${CONFIG_PATH}/${section}"
+	
+	set -- $SOCAT_CMD_ARGS
 
 	procd_open_instance "$section"
-	procd_set_param command $CMD
+	procd_set_param command "$BIN" "$@"
 	procd_set_param stdout 1
 	procd_set_param stderr 1
 	procd_close_instance
@@ -71,23 +99,25 @@ start_instance() {
 
 add_firewall_rule() {
 	local section="$1"
+	load_config_values "$section"
+
 	[ "$firewall_accept" != "1" ] && return 0
-	
-	config_get family "$section" family
-	[ "$family" = "4/6" ] && family=""
+
+	local ipv4=false
+	local ipv6=false
+	case "$family" in
+		4) ipv4=true ;;
+		6) ipv6=true ;;
+		4/6) ipv4=true; ipv6=true ;;
+		*) echo "Invalid firewall family in [$section]" >&2; return 1 ;;
+	esac
 
 	if $NFTABLES; then
-		if [ -z "$family" ]; then
-			echo "	$proto dport $listen_port accept" >> /var/etc/$CONFIG.include.nft
-		else
-			[ "$family" = "6" ] || family=4
-			echo "	meta nfproto ipv$family $proto dport $listen_port accept" >> /var/etc/$CONFIG.include.nft
-		fi
+		$ipv4 && echo "	meta nfproto ipv4 $proto dport $listen_port accept" >> /var/etc/$CONFIG.include.nft
+		$ipv6 && echo "	meta nfproto ipv6 $proto dport $listen_port accept" >> /var/etc/$CONFIG.include.nft
 	else
-		[ -z "$family" ] || [ "$family" = "6" ] && \
-			ip6tables -A SOCAT -p $proto --dport $listen_port -m comment --comment "$remarks" -j ACCEPT
-		[ -z "$family" ] || [ "$family" = "4" ] && \
-			iptables -A SOCAT -p $proto --dport $listen_port -m comment --comment "$remarks" -j ACCEPT
+		$ipv4 && iptables -A SOCAT -p $proto --dport $listen_port -m comment --comment "$remarks" -j ACCEPT
+		$ipv6 && ip6tables -A SOCAT -p $proto --dport $listen_port -m comment --comment "$remarks" -j ACCEPT
 	fi
 }
 
@@ -168,13 +198,7 @@ stop_service() {
 	rm -rf "$CONFIG_PATH"
 }
 
-reload_service() {
-	stop
-	start
-}
-
 service_triggers() {
 	procd_add_reload_trigger "$CONFIG"
 }
-
 
