Initial commit

diff --git a/luci-app-virtualhere/root/etc/init.d/vhusbd b/luci-app-virtualhere/root/etc/init.d/vhusbd
--- a/luci-app-virtualhere/root/etc/init.d/vhusbd
+++ b/luci-app-virtualhere/root/etc/init.d/vhusbd
@@ -2,19 +2,29 @@
 # Copyright (C) 2008-2020 OpenWrt.org
 
 START=99
-USE_PROCD=1
+
+echo "Starting vhusbd service..." >> /tmp/my_script_log.txt
+vhusbd -b -c /etc/config/vhusbdconfig -r /tmp/vhusbd.log >> /tmp/my_script_log.txt 2>&1
+echo "vhusbd service started with exit code: $?" >> /tmp/my_script_log.txt
 
 start_instance() {
     local cfg="$1"
     config_get_bool enabled "$cfg" 'enabled' '0'
     config_get_bool ExtAccess "$cfg" 'ExtAccess' '0'
-#   echo "enabled=$enabled,ExtAccess=$ExtAccess">>/tmp/tmp/vhusbd
+    
+    if [ ! -x /usr/bin/vhusbd ]; then
+        chmod 755 /usr/bin/vhusbd
+    fi
+    
     if [ $enabled -eq 1 ]; then
         vhusbd -b -c /etc/config/vhusbdconfig -r /tmp/vhusbd.log
-#       echo "virtualhere start">>/tmp/tmp/vhusbd
-	if [ $ExtAccess -eq 1 ]; then
-            iptables -I INPUT -p tcp --dport 7575 -j ACCEPT -m comment --comment 'virtualhere port'
-#           echo "virtualhere open firwall">>/tmp/tmp/vhusbd
+        vhusbd_status=$?  # 获取命令执行的返回状态
+        if [ $vhusbd_status -eq 0 ]; then
+            if [ $ExtAccess -eq 1 ]; then
+                iptables -I INPUT -p tcp --dport 7575 -j ACCEPT -m comment --comment 'virtualhere port'
+            fi
+        else
+            echo "Failed to start vhusbd service. Exit code: $vhusbd_status"
         fi
     fi
 }
